version: '3'
services:
  strapi:
    image: strapi/strapi:3.5.2
    container_name: ${CONTAINER_NAME}
    restart: always
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: host.docker.internal
      DATABASE_PORT: 5432
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
    volumes:
      - ./app:/srv/app
    ports:
      - "${PORT}:1337"
    extra_hosts: 
      - "host.docker.internal:host-gateway"
