services:
  db:
    image: postgres:15-alpine
    container_name: ${CONTAINER_NAME}_db
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./db-entrypoint:/docker-entrypoint-initdb.d
  strapi:
    image: strapi/strapi:3.5.2
    container_name: ${CONTAINER_NAME}
    restart: always
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
    volumes:
      - ./app:/srv/app
    ports:
      - "${PORT}:1337"
