version: '3'
services:
  strapi:
    image: strapi/strapi:3.6.8-alpine
    container_name: ${CONTAINER_NAME}
    restart: always
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: 162.214.108.8
      DATABASE_PORT: 5432
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./app:/srv/app
    ports:
      - "${PORT}:1337"
